apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo Hello Everyone!; sleep 2; done;"]
    
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80